version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: lifeline-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - ai-server

  backend:
    build: ./server
    container_name: lifeline
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/lifeline-db
    depends_on:
      - mongo


  ai-server:
    build: ./chatbot
    container_name: ai-server
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./chatbot/.env
    depends_on:
      - mongo
      - backend


  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
