version: "3.8"

services:
  backend:
    build: .
    container_name: lifeline
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/lifeline-db
      - PORT=8000
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
